logging:
  level:
    org:
      hibernate:
        SQL: TRACE
server:
  error:
    whitelabel:
      enabled: true
  port: 8081
spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    hikari:
      connection-timeout: 60000
      maximum-pool-size: 2
      minimum-idle: 1
      pool-name: data-source
    url: jdbc:mysql://localhost:3306/keyist?useSSL=false&allowPublicKeyRetrieval=true&useUnicode=yes&characterEncoding=UTF-8
    password: 1234
    username: root
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect
        format_sql: true
  mvc:
    throw-exception-if-no-handler-found: true
